import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
from matplotlib.patches import Rectangle

fig, ax = plt.subplots()
ax.set_xlim(0, 34)
ax.set_ylim(0, 36)
ax.set_aspect('equal')

ax.xaxis.set_major_locator(MultipleLocator(1))
ax.yaxis.set_major_locator(MultipleLocator(1))
ax.grid(True, linewidth=0.3, color='gray')

# Добавляем прямоугольники (все Y увеличены на 2)
rect = Rectangle((10, 30), 11, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((8, 29), 2, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((21, 29), 2, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((2, 28), 6, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((23, 28), 6, 1, facecolor='black')
ax.add_patch(rect)

rect = Rectangle((2, 26), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((28, 26), 1, 2, facecolor='black')
ax.add_patch(rect)

rect = Rectangle((3, 24), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((4, 23), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((5, 19), 1, 4, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((6, 17), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((7, 16), 1, 1, facecolor='black')
ax.add_patch(rect)

rect = Rectangle((27, 24), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((26, 23), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((25, 19), 1, 4, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((24, 17), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((23, 16), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((8, 15), 15, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((10, 14), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((9, 9), 1, 5, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((10, 5), 1, 4, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((11, 2), 1, 3, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((12, 1), 2, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((14, 2), 1, 5, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((15, 1), 9, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((17, 2), 1, 3, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((18, 5), 1, 4, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((24, 2), 3, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((25, 3), 1, 7, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((24, 10), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((23, 12), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((22, 13), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((21, 14), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((27, 3), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((28, 4), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((29, 5), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((30, 6), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((31, 8), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((32, 9), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((31, 11), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((30, 12), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((27, 13), 3, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((27, 12), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((28, 11), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((29, 9), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((28, 7), 1, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((27, 6), 1, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((26, 5), 1, 1, facecolor='black')
ax.add_patch(rect)


rect = Rectangle((8, 19), 4, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((19, 19), 4, 2, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((9, 21), 2, 1, facecolor='black')
ax.add_patch(rect)
rect = Rectangle((9, 18), 2, 1, facecolor='black')
ax.add_patch(rect)




plt.show()
